-- DROP TABLE if EXISTS Users;
-- DROP TABLE if EXISTS Songs;
-- DROP TABLE if EXISTS Playlists;
CREATE TABLE Users
(id INTEGER NOT NULL PRIMARY KEY,
 name VARCHAR(256) NOT NULL);
CREATE TABLE Songs
(songId INTEGER NOT NULL,
 userId INTEGER NOT NULL References Users(id),
 songTitle VARCHAR(256) NOT NULL,
 songArtist VARCHAR(256),
 playlistId INTEGER NOT NULL);
CREATE TABLE Playlists
 (userId INTEGER NOT NULL REFERENCES Users(id),
 playlistId INTEGER NOT NULL,
 songId INTEGER NOT NULL);